[project]
name = "strengths"
version = "0.0.16"
authors = [
	{name = "Thibault Fillion"},
	{name = "Francesco Piazza"}]
description = "A package for the modeling and simulation of reaction-diffusion systems."
readme = "README.rst"
dependencies = [
	"numpy",
	"matplotlib"]
